"""initial

Revision ID: 0ad4b30ee486
Revises: f12aec262a38
Create Date: 2024-08-10 16:23:51.194455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ad4b30ee486'
down_revision: Union[str, None] = 'f12aec262a38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pckundalikcom', 'token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pckundalikcom', sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
