"""Awdawd

Revision ID: 2806dafcdc0f
Revises: 8dd9e7452902
Create Date: 2024-09-06 18:02:17.945602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2806dafcdc0f'
down_revision: Union[str, None] = '8dd9e7452902'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tulov_summasi', sa.BigInteger(), nullable=True),
    sa.Column('payment_chek_img', sa.LargeBinary(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_admin_id'), 'payment', ['admin_id'], unique=False)
    op.create_index(op.f('ix_payment_id'), 'payment', ['id'], unique=False)
    op.create_index(op.f('ix_payment_user_id'), 'payment', ['user_id'], unique=False)
    op.add_column('admins', sa.Column('full_name', sa.String(length=25), nullable=True))
    op.add_column('admins', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('admins', sa.Column('email', sa.String(), nullable=True))
    op.add_column('admins', sa.Column('sex', sa.Boolean(), nullable=True))
    op.add_column('admins', sa.Column('premessions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('admins', sa.Column('code', sa.BigInteger(), nullable=True))
    op.add_column('admins', sa.Column('reset_code', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=True)
    op.create_index(op.f('ix_admins_full_name'), 'admins', ['full_name'], unique=False)
    op.create_index(op.f('ix_admins_phone'), 'admins', ['phone'], unique=True)
    op.create_index(op.f('ix_admins_premessions'), 'admins', ['premessions'], unique=False)
    op.create_index(op.f('ix_admins_token'), 'admins', ['token'], unique=True)
    op.drop_column('forregister', 'expires_at')
    op.add_column('products', sa.Column('logo', sa.LargeBinary(), nullable=True))
    op.add_column('products', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('products', sa.Column('updated_at', sa.TIMESTAMP(), nullable=True))
    op.alter_column('products', 'settings',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.add_column('reportsbalance', sa.Column('payment_number', sa.BigInteger(), nullable=True))
    op.add_column('reportsbalance', sa.Column('tulov_summasi', sa.BigInteger(), nullable=True))
    op.alter_column('reportsbalance', 'balance',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.create_index(op.f('ix_reportsbalance_payment_number'), 'reportsbalance', ['payment_number'], unique=False)
    op.create_index(op.f('ix_reportsbalance_user_id'), 'reportsbalance', ['user_id'], unique=False)
    op.create_foreign_key(None, 'reportsbalance', 'users', ['user_id'], ['id'])
    op.drop_column('reportsbalance', 'size')
    op.add_column('school_data', sa.Column('school_name', sa.String(), nullable=True))
    op.drop_column('school_data', 'school_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school_data', sa.Column('school_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('school_data', 'school_name')
    op.add_column('reportsbalance', sa.Column('size', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'reportsbalance', type_='foreignkey')
    op.drop_index(op.f('ix_reportsbalance_user_id'), table_name='reportsbalance')
    op.drop_index(op.f('ix_reportsbalance_payment_number'), table_name='reportsbalance')
    op.alter_column('reportsbalance', 'balance',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('reportsbalance', 'tulov_summasi')
    op.drop_column('reportsbalance', 'payment_number')
    op.alter_column('products', 'settings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('products', 'updated_at')
    op.drop_column('products', 'created_at')
    op.drop_column('products', 'logo')
    op.add_column('forregister', sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_admins_token'), table_name='admins')
    op.drop_index(op.f('ix_admins_premessions'), table_name='admins')
    op.drop_index(op.f('ix_admins_phone'), table_name='admins')
    op.drop_index(op.f('ix_admins_full_name'), table_name='admins')
    op.drop_index(op.f('ix_admins_email'), table_name='admins')
    op.drop_column('admins', 'reset_code')
    op.drop_column('admins', 'code')
    op.drop_column('admins', 'premessions')
    op.drop_column('admins', 'sex')
    op.drop_column('admins', 'email')
    op.drop_column('admins', 'phone')
    op.drop_column('admins', 'full_name')
    op.drop_index(op.f('ix_payment_user_id'), table_name='payment')
    op.drop_index(op.f('ix_payment_id'), table_name='payment')
    op.drop_index(op.f('ix_payment_admin_id'), table_name='payment')
    op.drop_table('payment')
    # ### end Alembic commands ###
