"""Create iqromindtest table

Revision ID: 36600e94009f
Revises: 7b8db0e0c68c
Create Date: 2024-12-16 22:02:52.227858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '36600e94009f'
down_revision: Union[str, None] = '7b8db0e0c68c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('iqromindtest', sa.Column('edit_token', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('iqromindtest', 'edit_token')
    # ### end Alembic commands ###
