"""modelsga id columnga autoincrement=True qo'shildi

Revision ID: 589ab9f56610
Revises: e2a91a68382b
Create Date: 2024-08-03 17:20:18.177519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '589ab9f56610'
down_revision: Union[str, None] = 'e2a91a68382b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
