"""Create iqromindtest table

Revision ID: 7b8db0e0c68c
Revises: 5dfcb31f308b
Create Date: 2024-12-16 19:00:08.919172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b8db0e0c68c'
down_revision: Union[str, None] = '5dfcb31f308b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iqrominddevices',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_index(op.f('ix_iqrominddevices_user_id'), 'iqrominddevices', ['user_id'], unique=True)
    op.create_table('iqromindtest',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('testlar', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('edu_name', sa.String(), nullable=True),
    sa.Column('edu_log', sa.String(), nullable=True),
    sa.Column('edu_bot_token', sa.String(), nullable=True),
    sa.Column('end_premium_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('end_use_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_iqromindtest_id'), 'iqromindtest', ['id'], unique=False)
    op.create_index(op.f('ix_iqromindtest_user_id'), 'iqromindtest', ['user_id'], unique=False)
    op.alter_column('payment', 'payment_chek_img',
               existing_type=postgresql.BYTEA(),
               type_=sa.String(length=700),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment', 'payment_chek_img',
               existing_type=sa.String(length=700),
               type_=postgresql.BYTEA(),
               existing_nullable=True)
    op.drop_index(op.f('ix_iqromindtest_user_id'), table_name='iqromindtest')
    op.drop_index(op.f('ix_iqromindtest_id'), table_name='iqromindtest')
    op.drop_table('iqromindtest')
    op.drop_index(op.f('ix_iqrominddevices_user_id'), table_name='iqrominddevices')
    op.drop_table('iqrominddevices')
    # ### end Alembic commands ###
