"""Initial migration

Revision ID: 7bcf92ffff6f
Revises: 8f90d2b1a883
Create Date: 2024-08-05 15:21:27.710021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bcf92ffff6f'
down_revision: Union[str, None] = '8f90d2b1a883'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('forregister_phone_unique', 'forregister', type_='unique')
    op.create_index(op.f('ix_users_tg_id'), 'users', ['tg_id'], unique=True)
    op.drop_constraint('users_phone_fkey', 'users', type_='foreignkey')
    op.drop_constraint('users_tg_id_fkey', 'users', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('users_tg_id_fkey', 'users', 'forregister', ['tg_id'], ['tg_id'])
    op.create_foreign_key('users_phone_fkey', 'users', 'forregister', ['phone'], ['phone'])
    op.drop_index(op.f('ix_users_tg_id'), table_name='users')
    op.create_unique_constraint('forregister_phone_unique', 'forregister', ['phone'])
    # ### end Alembic commands ###
