"""initial migration

Revision ID: 85136ff7e92a
Revises: 
Create Date: 2024-11-24 21:05:18.832829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '85136ff7e92a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=25), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('sex', sa.Boolean(), nullable=True),
    sa.Column('tg_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('premessions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('token', sa.String(length=700), nullable=True),
    sa.Column('code', sa.BigInteger(), nullable=True),
    sa.Column('reset_code', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=True)
    op.create_index(op.f('ix_admins_full_name'), 'admins', ['full_name'], unique=False)
    op.create_index(op.f('ix_admins_id'), 'admins', ['id'], unique=False)
    op.create_index(op.f('ix_admins_phone'), 'admins', ['phone'], unique=True)
    op.create_index(op.f('ix_admins_premessions'), 'admins', ['premessions'], unique=False)
    op.create_index(op.f('ix_admins_tg_id'), 'admins', ['tg_id'], unique=True)
    op.create_index(op.f('ix_admins_token'), 'admins', ['token'], unique=True)
    op.create_table('majburiyobuna',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_majburiyobuna_id'), 'majburiyobuna', ['id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('logo', sa.LargeBinary(), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=25), nullable=True),
    sa.Column('sex', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('username', sa.String(length=30), nullable=True),
    sa.Column('password', sa.String(length=260), nullable=True),
    sa.Column('tg_id', sa.BigInteger(), nullable=True),
    sa.Column('balance', sa.BigInteger(), nullable=True),
    sa.Column('ref_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('last_login', sa.TIMESTAMP(), nullable=True),
    sa.Column('code', sa.BigInteger(), nullable=True),
    sa.Column('reset_code', sa.BigInteger(), nullable=True),
    sa.Column('how_online', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('activation_token', sa.String(length=700), nullable=True),
    sa.Column('token', sa.String(length=700), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_activation_token'), 'users', ['activation_token'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_tg_id'), 'users', ['tg_id'], unique=True)
    op.create_index(op.f('ix_users_token'), 'users', ['token'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('loginsdata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('login', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loginsdata_id'), 'loginsdata', ['id'], unique=False)
    op.create_index(op.f('ix_loginsdata_user_id'), 'loginsdata', ['user_id'], unique=False)
    op.create_table('mobilekundalikcom',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('start_active_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('end_active_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('end_use_date', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mobilekundalikcom_id'), 'mobilekundalikcom', ['id'], unique=False)
    op.create_index(op.f('ix_mobilekundalikcom_user_id'), 'mobilekundalikcom', ['user_id'], unique=False)
    op.create_table('payment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tulov_summasi', sa.BigInteger(), nullable=True),
    sa.Column('payment_chek_img', sa.String(length=700), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_admin_id'), 'payment', ['admin_id'], unique=False)
    op.create_index(op.f('ix_payment_id'), 'payment', ['id'], unique=False)
    op.create_index(op.f('ix_payment_user_id'), 'payment', ['user_id'], unique=False)
    op.create_table('pckundalikcom',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('start_active_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('end_active_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('end_use_date', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pckundalikcom_id'), 'pckundalikcom', ['id'], unique=False)
    op.create_index(op.f('ix_pckundalikcom_user_id'), 'pckundalikcom', ['user_id'], unique=False)
    op.create_table('reportsbalance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('payment_number', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('balance', sa.BigInteger(), nullable=True),
    sa.Column('tulov_summasi', sa.BigInteger(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reportsbalance_id'), 'reportsbalance', ['id'], unique=False)
    op.create_index(op.f('ix_reportsbalance_payment_number'), 'reportsbalance', ['payment_number'], unique=False)
    op.create_index(op.f('ix_reportsbalance_user_id'), 'reportsbalance', ['user_id'], unique=False)
    op.create_table('school_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('viloyat', sa.String(), nullable=True),
    sa.Column('tuman', sa.String(), nullable=True),
    sa.Column('school_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_school_data_id'), 'school_data', ['id'], unique=False)
    op.create_index(op.f('ix_school_data_user_id'), 'school_data', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_school_data_user_id'), table_name='school_data')
    op.drop_index(op.f('ix_school_data_id'), table_name='school_data')
    op.drop_table('school_data')
    op.drop_index(op.f('ix_reportsbalance_user_id'), table_name='reportsbalance')
    op.drop_index(op.f('ix_reportsbalance_payment_number'), table_name='reportsbalance')
    op.drop_index(op.f('ix_reportsbalance_id'), table_name='reportsbalance')
    op.drop_table('reportsbalance')
    op.drop_index(op.f('ix_pckundalikcom_user_id'), table_name='pckundalikcom')
    op.drop_index(op.f('ix_pckundalikcom_id'), table_name='pckundalikcom')
    op.drop_table('pckundalikcom')
    op.drop_index(op.f('ix_payment_user_id'), table_name='payment')
    op.drop_index(op.f('ix_payment_id'), table_name='payment')
    op.drop_index(op.f('ix_payment_admin_id'), table_name='payment')
    op.drop_table('payment')
    op.drop_index(op.f('ix_mobilekundalikcom_user_id'), table_name='mobilekundalikcom')
    op.drop_index(op.f('ix_mobilekundalikcom_id'), table_name='mobilekundalikcom')
    op.drop_table('mobilekundalikcom')
    op.drop_index(op.f('ix_loginsdata_user_id'), table_name='loginsdata')
    op.drop_index(op.f('ix_loginsdata_id'), table_name='loginsdata')
    op.drop_table('loginsdata')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_token'), table_name='users')
    op.drop_index(op.f('ix_users_tg_id'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_activation_token'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_majburiyobuna_id'), table_name='majburiyobuna')
    op.drop_table('majburiyobuna')
    op.drop_index(op.f('ix_admins_token'), table_name='admins')
    op.drop_index(op.f('ix_admins_tg_id'), table_name='admins')
    op.drop_index(op.f('ix_admins_premessions'), table_name='admins')
    op.drop_index(op.f('ix_admins_phone'), table_name='admins')
    op.drop_index(op.f('ix_admins_id'), table_name='admins')
    op.drop_index(op.f('ix_admins_full_name'), table_name='admins')
    op.drop_index(op.f('ix_admins_email'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
