"""initial

Revision ID: 8dd9e7452902
Revises: 43b50f4e2767
Create Date: 2024-08-10 17:42:11.660936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dd9e7452902'
down_revision: Union[str, None] = '43b50f4e2767'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mobilekundalikcom', sa.Column('end_use_date', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mobilekundalikcom', 'end_use_date')
    # ### end Alembic commands ###
