"""modelsga id columnga autoincrement=True qo'shildi

Revision ID: 8f90d2b1a883
Revises: 589ab9f56610
Create Date: 2024-08-04 14:44:58.035207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f90d2b1a883'
down_revision: Union[str, None] = '589ab9f56610'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
