"""initial migration

Revision ID: ad77a140cd37
Revises: 4c79e6b7e04e
Create Date: 2024-08-09 16:12:13.531531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad77a140cd37'
down_revision: Union[str, None] = '4c79e6b7e04e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('settings', sa.JSON(), nullable=True))
    op.drop_index('ix_products_user_id', table_name='products')
    op.drop_constraint('products_user_id_fkey', 'products', type_='foreignkey')
    op.drop_column('products', 'price')
    op.drop_column('products', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('products_user_id_fkey', 'products', 'users', ['user_id'], ['id'])
    op.create_index('ix_products_user_id', 'products', ['user_id'], unique=False)
    op.drop_column('products', 'settings')
    # ### end Alembic commands ###
