"""initial

Revision ID: f12aec262a38
Revises: 95cac4ecdd2e
Create Date: 2024-08-10 03:08:41.293123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f12aec262a38'
down_revision: Union[str, None] = '95cac4ecdd2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reportsbalance_user_id', table_name='reportsbalance')
    op.drop_constraint('reportsbalance_user_id_fkey', 'reportsbalance', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('reportsbalance_user_id_fkey', 'reportsbalance', 'users', ['user_id'], ['id'])
    op.create_index('ix_reportsbalance_user_id', 'reportsbalance', ['user_id'], unique=False)
    # ### end Alembic commands ###
